services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Map the container's port to your local machine
    volumes:
      - .:/app # Mount the current directory to the container
      - /app/node_modules # Prevent overwriting node_modules
    stdin_open: true
    tty: true